image: Visual Studio 2017
platform: Any CPU

environment:
  version: $(APPVEYOR_BUILD_VERSION)

configuration:
- Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%version%'
  package_version: '%version%'
  assembly_version: '%version%'
  file_version: '%version%'
  informational_version: '%version%'

build:
  project: Serilog.Sinks.InfluxDB.sln

after_test:
  - dotnet pack --configuration Release /p:Version=%version%

artifacts:
  - path: Serilog.Sinks.InfluxDB\bin\Release\netstandard2.0\Serilog.Sinks.InfluxDB.dll
    name: Serilog.Sinks.InfluxDB.dll
  - path: Serilog.Sinks.InfluxDB\bin\Release\Serilog.Sinks.InfluxDB.Standard.%version%.nupkg
    name: Serilog.Sinks.InfluxDB.Standard.%version%.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: csyDlyeSjDmdYAQ/PK0GYNZ4ofK/yC6vd5ZLPnG2TgujmrAW7fUiQxjDVOWD4XAX